sudo: false
language: scala
jdk: oraclejdk8

jobs:
  include:
     - stage: test
       script: sbt scripted

     - stage: publish
       script: sbt publish

stages:
  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo master commits or version-tagged commits
  - name: publish
    if: repo = sbt/sbt-java-formatter AND ( ( branch = master AND type = push ) OR tag =~ ^v )


before_cache:
  - find $HOME/.ivy2/ -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt   -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "eu2N7/NQhW/FxZlo8EYNN87We56suS74P63gdJOmrJCNR/b1Y2TL1QwpywkHCvGZep6OQX67SjtoB6PRgAnkrX/lniXRNtwGpj23j1geVK2xj1Qn7da+X34beLuhMYWwgRSNgLOOGplbdWdMXkcmidbNBUSb00N3qI54/EwqwsQ="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "Gh6GmXpP1UOSZ+8EI9N7mwCojNwq6oINccnWk6GNbKEFxkPRMSsF1UQnvUalMT9ukgRO9UFnKvBbHD2XEY/2K+0OxjLXJzCog9DblCLSii9tWrwuVGCl0cQhakgIP5H8NHqdFe1dxZE8nEVabiuatywlT8LYjn7UQ9Kuh97nR5o="
